name: deepvoice
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6.9
  - pip=19.2.2
  - cython=0.29.13
  - fastdtw=0.3.2
  - numba=0.45.1
  - pytorch=1.2.0
  - tensorflow=1.14.0
  - tensorflow-gpu=1.14.0
  - tensorboard=1.14.0
  - tensorboardx=1.2
  - numpy=1.16.4
  - scipy=1.3.1
  - scikit-learn=0.21.3
  - matplotlib=3.1.1
  - nltk=3.4.4
  - librosa=0.7.0
  - inflect=2.1.0
  - tqdm=4.35.0
  - docopt=0.6.2
  - unidecode=1.1.1
  - jupyter
  - nb_conda
  - nb_conda_kernels
  - pillow=6.1.0
  - pip:
    - nnmnkwii==0.0.19
    - lws<=1.0
